In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Count the number of educational level 
df = pd.read_csv('Week4_1_data.csv')
grouped_df = df.groupby('educational_level')['customer_id'].count()
grouped_df

educational_level
Basic            7
Graduation     257
High School     40
Master          81
PhD            114
Name: customer_id, dtype: int64

In [4]:
df

,customer_id,year_of_birth,educational_level,marital_status,annual_income,purhcase_date,recency,online_purchases,store_purchases,complaints,calls,intercoms
0,20201701,1982,Graduation,Single,58138.0,9/4/2012,58,8,4,0,3,11
1,20201702,1950,Graduation,Married,46344.0,3/8/2014,38,1,2,0,3,11
2,20201703,1965,Graduation,Divorced,71613.0,8/21/2013,26,8,10,0,3,11
3,20201704,1984,Graduation,Relationship,26646.0,2/10/2014,26,2,4,0,3,11
4,20201705,1981,PhD,Widowed,58293.0,1/19/2014,94,5,6,0,3,11
...,...,...,...,...,...,...,...,...,...,...,...,...
494,20202195,1944,PhD,Divorced,55614.0,11/27/2013,85,9,6,0,3,11
495,20202196,1962,Master,Divorced,59432.0,4/13/2013,88,5,11,0,3,11
496,20202197,1978,Graduation,Divorced,55563.0,4/5/2014,22,2,3,0,3,11
497,20202198,1971,PhD,Relationship,43624.0,4/21/2013,83,4,4,0,6,11
498,20202199,1949,PhD,Relationship,41461.0,5/22/2014,63,6,11,0,6,11

In [5]:
# Sort 20 people have highest income
top_20_people = df.sort_values(by="annual_income", ascending=False).head(20)
top_20_people

,customer_id,year_of_birth,educational_level,marital_status,annual_income,purhcase_date,recency,online_purchases,store_purchases,complaints,calls,intercoms
164,20201865,1952,PhD,Relationship,157243.0,3/1/2014,98,0,0,0,3,11
252,20201953,1997,Graduation,Widowed,102692.0,4/5/2013,5,6,13,0,3,11
203,20201904,1989,PhD,Single,102160.0,11/2/2012,54,7,10,0,4,11
124,20201825,1957,Graduation,Single,101970.0,3/12/2013,69,6,13,0,3,11
424,20202125,1967,PhD,Married,93027.0,4/13/2013,77,7,5,0,3,11
426,20202127,1957,Graduation,Married,92910.0,4/24/2014,42,6,13,0,3,11
140,20201841,1987,Master,Single,92859.0,10/19/2012,46,5,12,0,3,2
418,20202119,2000,Graduation,Single,91065.0,2/22/2013,33,7,9,0,3,11
116,20201817,2000,Graduation,Relationship,90765.0,1/24/2014,25,4,5,0,3,11
456,20202157,1957,High School,Single,89572.0,9/15/2012,44,7,9,0,3,11
109,20201810,1993,Master,Single,89058.0,12/7/2012,18,5,4,0,3,7
67,20201768,1984,High School,Divorced,88194.0,3/19/2014,19,11,10,1,3,11
120,20201821,1957,Master,Relationship,88193.0,6/20/2013,65,6,10,0,5,11
198,20201899,1984,Graduation,Widowed,86718.0,1/17/2013,20,5,5,0,3,2
407,20202108,1989,PhD,Relationship,86164.0,5/30/2014,1,5,5,0,8,11
142,20201843,1989,Graduation,Divorced,86111.0,4/19/2013,73,5,10,0,3,11
113,20201814,1997,Graduation,Married,86037.0,1/2/2013,95,6,11,0,3,6
102,20201803,1986,Graduation,Relationship,85693.0,4/20/2013,59,9,11,0,3,7
356,20202057,1955,Graduation,Relationship,85503.0,5/11/2013,61,6,4,0,3,11
195,20201896,1981,Graduation,Relationship,85317.0,12/29/2013,24,1,2,0,0,2

In [10]:
# Customers who were born after 1960 and have annual_income > 50,000
filtered_customers = df[(df['year_of_birth'] > 1960) & (df['annual_income'] > 50000)]
print(filtered_customers)

     customer_id  year_of_birth educational_level marital_status  \
0       20201701           1982        Graduation         Single
2       20201703           1965        Graduation       Divorced
4       20201705           1981               PhD        Widowed
5       20201706           1967            Master   Relationship
6       20201707           1971        Graduation       Divorced
..           ...            ...               ...            ...
486     20202187           1976            Master   Relationship
487     20202188           1974        Graduation        Married
493     20202194           1964            Master         Single
495     20202196           1962            Master       Divorced
496     20202197           1978        Graduation       Divorced

     annual_income purhcase_date  recency  online_purchases  store_purchases  \
0          58138.0      9/4/2012       58                 8                4
2          71613.0     8/21/2013       26                 8               10
4          58293.0     1/19/2014       94                 5                6
5          62000.0      9/9/2013       16                 6               10
6          55635.0    11/13/2012       34                 7                7
..             ...           ...      ...               ...              ...
486        56290.0    11/14/2013        4                 3                7
487        60093.0     6/26/2013       92                 7               10
493        58308.0     1/12/2013       77                 2                3
495        59432.0     4/13/2013       88                 5               11
496        55563.0      4/5/2014       22                 2                3

     complaints  calls  intercoms
0             0      3         11
2             0      3         11
4             0      3         11
5             5      3         11
6             0      3         11
..          ...    ...        ...
486           0     11         11
487           0      3         11
493           0      3         11
495           0      3         11
496           0      3         11

[206 rows x 12 columns]

In [11]:
top_20_people_2 = filtered_customers.sort_values(by='annual_income', ascending=False).head(20)
top_20_people

,customer_id,year_of_birth,educational_level,marital_status,annual_income,purhcase_date,recency,online_purchases,store_purchases,complaints,calls,intercoms
164,20201865,1952,PhD,Relationship,157243.0,3/1/2014,98,0,0,0,3,11
252,20201953,1997,Graduation,Widowed,102692.0,4/5/2013,5,6,13,0,3,11
203,20201904,1989,PhD,Single,102160.0,11/2/2012,54,7,10,0,4,11
124,20201825,1957,Graduation,Single,101970.0,3/12/2013,69,6,13,0,3,11
424,20202125,1967,PhD,Married,93027.0,4/13/2013,77,7,5,0,3,11
426,20202127,1957,Graduation,Married,92910.0,4/24/2014,42,6,13,0,3,11
140,20201841,1987,Master,Single,92859.0,10/19/2012,46,5,12,0,3,2
418,20202119,2000,Graduation,Single,91065.0,2/22/2013,33,7,9,0,3,11
116,20201817,2000,Graduation,Relationship,90765.0,1/24/2014,25,4,5,0,3,11
456,20202157,1957,High School,Single,89572.0,9/15/2012,44,7,9,0,3,11
109,20201810,1993,Master,Single,89058.0,12/7/2012,18,5,4,0,3,7
67,20201768,1984,High School,Divorced,88194.0,3/19/2014,19,11,10,1,3,11
120,20201821,1957,Master,Relationship,88193.0,6/20/2013,65,6,10,0,5,11
198,20201899,1984,Graduation,Widowed,86718.0,1/17/2013,20,5,5,0,3,2
407,20202108,1989,PhD,Relationship,86164.0,5/30/2014,1,5,5,0,8,11
142,20201843,1989,Graduation,Divorced,86111.0,4/19/2013,73,5,10,0,3,11
113,20201814,1997,Graduation,Married,86037.0,1/2/2013,95,6,11,0,3,6
102,20201803,1986,Graduation,Relationship,85693.0,4/20/2013,59,9,11,0,3,7
356,20202057,1955,Graduation,Relationship,85503.0,5/11/2013,61,6,4,0,3,11
195,20201896,1981,Graduation,Relationship,85317.0,12/29/2013,24,1,2,0,0,2

In [14]:
average_income_by_education = df.groupby('educational_level')['annual_income'].mean()
average_income_by_education

educational_level
Basic          19514.571429
Graduation     51607.827309
High School    44154.717949
Master         51191.700000
PhD            55878.990991
Name: annual_income, dtype: float64

As can be seen, the most people who get high income must be graduation from university. It doesn't mean that you have a high degree like master or PhD and you have a high income. Most people who graduation get higher income than the PhD and Master